### PR TITLE
Add 64Bit support for floats

### PR DESCRIPTION
**Pull request by flippinjoe21**
On 64Bit systems the doubleValue is being truncated when being sent to properties of 'float' type.   Example being CALayer.shadowOpacity.

This PR creates a dedicated primitive conversion for Float types to handle this truncation

### CODE REVIEW

**Comment by ryang1428** [comment]
:+1:

**Comment by flippinjoe21** [comment]
@cloudkite Sorry for the big PR.   The float / double fix turned out to break some tests, then I noticed some other tests were failing as well, so I went ahead and cleaned those up.   Let me know if you've got any questions

**Comment by cloudkite** [comment]
@flippinjoe21 No problem, at first glance looks great. Will hopefully review in next couple of days

**Comment by cloudkite** [comment]
@flippinjoe21 looks great, Thanks!

**Pull request merged**
